## 9.1.1 k-평균

In [1]:
import numpy as np
from sklearn.datasets import make_blobs

blob_centers = np.array(
    [[ 0.2,  2.3],
     [-1.5 ,  2.3],
     [-2.8,  1.8],
     [-2.8,  2.8],
     [-2.8,  1.3]])
blob_std = np.array([0.4, 0.3, 0.1, 0.1, 0.1])

X, y = make_blobs(n_samples=2000, centers=blob_centers,
                  cluster_std=blob_std, random_state=7)

In [2]:
"""
데이터셋에 K-평균 군집 알고리즘을 훈련
이 알고리즘은 클러스터 중심을 찾고 각 샘플을 가까운 클러스터에 할당한다.
"""
from sklearn.cluster import KMeans

k = 5
kmeans = KMeans(n_clusters=k)
y_pred = kmeans.fit_predict(X)

/Users/ihaeyeong/Library/Python/3.9/lib/python/site-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


In [3]:
# 각 샘플은 5개의 클러스터 중 하나에 할당된다.
y_pred

array([1, 4, 0, ..., 2, 0, 4], dtype=int32)

In [4]:
y_pred is kmeans.labels_

True

In [5]:
# 5개의 센트로이드 (즉 클러스터 중심)
kmeans.cluster_centers_

array([[ 0.20876306,  2.25551336],
       [-2.80037642,  1.30082566],
       [-2.79290307,  2.79641063],
       [-1.46679593,  2.28585348],
       [-2.80389616,  1.80117999]])

In [6]:
kmeans.labels_

array([1, 4, 0, ..., 2, 0, 4], dtype=int32)

In [8]:
X_new = np.array([[0, 2], [3, 2], [-3, 3], [-3, 2.5]])
kmeans.predict(X_new)

array([0, 0, 2, 2], dtype=int32)